services:
  mongo-2:
    image: mongo:5.0.7
    container_name: mongo-2
    ports:
      - 27018:27018
  mongo-3:
    image: mongo:5.0.7
    container_name: mongo-3
    ports:
      - 27019:27019
  mongo-1:
    #image: mongo:5.0.7
      build: .
      container_name: mongo-1
      ports:
       - 27017:27017